- type: entity
  id: CrateSecurityIFF
  parent: CrateSecgear
  name: security IFF crate
  description: Contains twelve security IFF light sets. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: ClothingNeckIFFCyan
        amount: 12

- type: entity
  id: CrateBorgArmor
  parent: CrateSecgear
  name: synthetic armor crate
  description: Contains a variety pack of synthetic armor. For your aspiring silicon comrades.
  components:
  - type: StorageFill
    contents:
      - id: SyntheticBorgArmorLight
        amount: 1
      - id: SyntheticBorgArmorMedium
        amount: 1
      - id: SyntheticBorgArmorHeavy
        amount: 1

- type: entity
  id: CrateBorgLight
  parent: CrateSecgear
  name: light synthetic armor crate
  description: Contains two seperate sets of armor for your synthetic pals.
  components:
  - type: StorageFill
    contents:
      - id: SyntheticBorgArmorLight
        amount: 1
      - id: SyntheticBorgArmorLightShield
        amount: 1
